apiVersion: v1
description: Knative Helm chart for Kubernetes
name: knative
version: 0.1
appVersion: 0.1.1
home: https://github.com/knative/
icon: https://raw.githubusercontent.com/knative/docs/master/images/logo/rgb/knative-logo-rgb.jpg
sources:
- https://github.com/knative/
maintainers:
- name: Tunde Oladipupo
  email: tunde@aquatribe.com
- name: Babatunde Olu-isa
  email: babatunde@aquatribe.com
