{{- if .Values.eventing.install -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.eventing.serviceAccount.name }}
  namespace: {{ .Values.eventing.namespace }}
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bus-operator
  namespace: {{ .Values.eventing.namespace }}
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
