{{- if .Values.eventing.install -}}
{{ if .Values.rbac.enable }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-channels-bus
  labels:
      app: {{.Chart.Name}}-eventing
      chart: {{.Chart.Name}}-{{.Chart.Version}}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - channels.knative.dev
  resources:
  - buses
  - clusterbuses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - channels.knative.dev
  resources:
  - channels
  - subscriptions
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{ end }}
{{- end -}}
