{{- if .Values.eventing.install -}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buses.channels.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  group: channels.knative.dev
  names:
    categories:
    - all
    - knative
    - kbus
    - eventing
    kind: Bus
    plural: buses
    singular: bus
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: channels.channels.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: channels.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    kind: Channel
    plural: channels
    shortNames:
    - chan
    singular: channel
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterbuses.channels.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: channels.knative.dev
  names:
    categories:
    - all
    - knative
    - kbus
    - eventing
    kind: ClusterBus
    plural: clusterbuses
    shortNames:
    - cbus
    singular: clusterbus
  scope: Cluster
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustereventsources.feeds.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: feeds.knative.dev
  names:
    categories:
    - all
    - knative
    - keventsource
    - eventing
    kind: ClusterEventSource
    plural: clustereventsources
    singular: clustereventsource
  scope: Cluster
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustereventtypes.feeds.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: feeds.knative.dev
  names:
    categories:
    - all
    - knative
    - keventtype
    - eventing
    kind: ClusterEventType
    plural: clustereventtypes
    singular: clustereventsource
  scope: Cluster
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventsources.feeds.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: feeds.knative.dev
  names:
    categories:
    - all
    - knative
    - keventsource
    - eventing
    kind: EventSource
    plural: eventsources
    singular: eventsource
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventtypes.feeds.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: feeds.knative.dev
  names:
    categories:
    - all
    - knative
    - keventtype
    - eventing
    kind: EventType
    plural: eventtypes
    singular: eventtype
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: feeds.feeds.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: feeds.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    kind: Feed
    plural: feeds
    singular: feed
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flows.flows.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: flows.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    kind: Flow
    plural: flows
    singular: flow
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.channels.knative.dev
  labels:
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: channels.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    kind: Subscription
    plural: subscriptions
    shortNames:
    - sub
    singular: subscription
  scope: Namespaced
  version: v1alpha1
{{- end -}}
