{{- if .Values.eventing.install -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
    app: {{.Chart.Name}}-eventing
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: webhook
  namespace: {{ .Values.eventing.namespace }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    role: webhook
{{- end -}}
